//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PateintOrderDetail
    {
        public int OrderId { get; set; }
        public Nullable<int> PateintId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
